/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.fgk.ihm;

import fr.fgk.dao.ClientDao;
import fr.fgk.dao.CommandeDao;
import fr.fgk.dao.PlatChoisisDao;
import fr.fgk.dao.PlatDao;
import fr.fgk.model.Client;
import fr.fgk.model.Commande;
import fr.fgk.model.Plat;
import fr.fgk.model.PlatChoisis;
import fr.fgk.properties.PropertiesGlobals;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dylan55
 */
public class CommandeIhm extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public CommandeIhm() {
        initComponents();
        jLabel1.setText("Client: " + PropertiesGlobals.USER_CONNECT.getNom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ButtonSuivant1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TCommande = new javax.swing.JTable();
        CommanderBtn = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/fgk/img/bigking-1.png"))); // NOI18N
        jButton3.setAutoscrolls(true);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setLabelFor(jButton3);
        jLabel1.setText("Double burger = 15€");
        jLabel1.setToolTipText("");

        jButton9.setBackground(new java.awt.Color(153, 153, 153));
        jButton9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 51, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/fgk/img/steakhouse-6.png"))); // NOI18N
        jButton9.setAutoscrolls(true);
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(153, 153, 153));
        jButton10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 51, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/fgk/img/whooper-7.png"))); // NOI18N
        jButton10.setAutoscrolls(true);
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(153, 153, 153));
        jButton11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 51, 0));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/fgk/img/chickencrispy-2.png"))); // NOI18N
        jButton11.setAutoscrolls(true);
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(153, 153, 153));
        jButton12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 51, 0));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/fgk/img/eggburgersdouble3.png"))); // NOI18N
        jButton12.setAutoscrolls(true);
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(153, 153, 153));
        jButton13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 51, 0));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/fgk/img/eggburgers-4.png"))); // NOI18N
        jButton13.setAutoscrolls(true);
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(153, 153, 153));
        jButton14.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 51, 0));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/fgk/img/king_fish-8.png"))); // NOI18N
        jButton14.setAutoscrolls(true);
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(153, 153, 153));
        jButton15.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 51, 0));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/fgk/img/kingburger-5.png"))); // NOI18N
        jButton15.setAutoscrolls(true);
        jButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setLabelFor(jButton3);
        jLabel2.setText("Whooper burger = 14€");
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setLabelFor(jButton3);
        jLabel3.setText("Double egg burger = 18€");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setLabelFor(jButton3);
        jLabel4.setText("Egg burger = 15€");
        jLabel4.setToolTipText("");

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setLabelFor(jButton3);
        jLabel5.setText("King burger = 20€");
        jLabel5.setToolTipText("");

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setLabelFor(jButton3);
        jLabel6.setText("Steakhouse burger = 19€");
        jLabel6.setToolTipText("");

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setLabelFor(jButton3);
        jLabel7.setText("Chicken Crispy = 13€");
        jLabel7.setToolTipText("");

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setLabelFor(jButton3);
        jLabel8.setText("Fish burger =15€");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("MingLiU-ExtB", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Fast Good Kitchen");

        ButtonSuivant1.setBackground(new java.awt.Color(102, 255, 0));
        ButtonSuivant1.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        ButtonSuivant1.setForeground(new java.awt.Color(51, 51, 51));
        ButtonSuivant1.setText("Etape Suivante");
        ButtonSuivant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSuivant1ActionPerformed(evt);
            }
        });

        TCommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TCommande);

        CommanderBtn.setBackground(new java.awt.Color(255, 0, 51));
        CommanderBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CommanderBtn.setText("Terminer la commande");
        CommanderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommanderBtnActionPerformed(evt);
            }
        });

        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGap(244, 244, 244))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton11)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 4, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSuivant1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommanderBtn)
                    .addComponent(btRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(ButtonSuivant1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CommanderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(396, 396, 396))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// double burger
        String qte = JOptionPane.showInputDialog("Entrez la quantité souhaité: ");
        int quant = Integer.parseInt(qte);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");

        try {

            Client u = ClientDao.getByNom(PropertiesGlobals.USER_CONNECT.getNom());
            if (u != null) {

                PlatChoisis c = new PlatChoisis();
                c.setIdPlat(7);
                c.setQtePlatChoisi(quant);
                System.out.println("idPlat: " + c.getIdPlat());
                PlatChoisisDao.insertPlatsChoisis(c);
                Plat p = new Plat();
                p.setIdPlatDisp(c.getIdPlat());
                p = PlatDao.getPlatById(p.getIdPlatDisp());
            }
            List<Plat> panier = PlatDao.getAllPlatsDisp();

            //panier.add(u);
            PlatChoisis choix = PlatChoisisDao.getLastPlatChoisisById();
            Plat platDisp = PlatDao.getPlatById(7);

            model.addRow(new Object[]{
                platDisp.getPlatDispos(),
                choix.getQtePlatChoisi(),
                platDisp.getPrixPlatDispos() * quant

            }
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception: " + e.getMessage());
        }
        TCommande.setModel(model);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        // double egg burger
        String qte = JOptionPane.showInputDialog("Entrez la quantité souhaité: ");
        int quant = Integer.parseInt(qte);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");

        try {

            Client u = ClientDao.getByNom(PropertiesGlobals.USER_CONNECT.getNom());
            if (u != null) {

                PlatChoisis c = new PlatChoisis();
                c.setIdPlat(6);
                c.setQtePlatChoisi(quant);
                System.out.println("idPlat: " + c.getIdPlat());
                PlatChoisisDao.insertPlatsChoisis(c);

                Plat p = new Plat();
                p.setIdPlatDisp(c.getIdPlat());
                p = PlatDao.getPlatById(p.getIdPlatDisp());
            }
            List<Plat> panier = PlatDao.getAllPlatsDisp();
            //panier.add(u);
            PlatChoisis choix = PlatChoisisDao.getLastPlatChoisisById();
            Plat platDisp = PlatDao.getPlatById(6);
            model.addRow(new Object[]{
                platDisp.getPlatDispos(),
                choix.getQtePlatChoisi(),
                platDisp.getPrixPlatDispos() * quant

            }
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception: " + e.getMessage());
        }

        TCommande.setModel(model);


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        //whooper burger
        String qte = JOptionPane.showInputDialog("Entrez la quantité souhaité: ");
        int quant = Integer.parseInt(qte);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");
        try {
            Client u = ClientDao.getByNom(PropertiesGlobals.USER_CONNECT.getNom());
            if (u != null) {
                PlatChoisis c = new PlatChoisis();
                c.setIdPlat(8);
                c.setQtePlatChoisi(quant);
                System.out.println("idPlat: " + c.getIdPlat());
                PlatChoisisDao.insertPlatsChoisis(c);
                Plat p = new Plat();
                p.setIdPlatDisp(c.getIdPlat());
                p = PlatDao.getPlatById(p.getIdPlatDisp());
            }
            List<Plat> panier = PlatDao.getAllPlatsDisp();
            //panier.add(u);
            PlatChoisis choix = PlatChoisisDao.getLastPlatChoisisById();
            Plat platDisp = PlatDao.getPlatById(8);
            model.addRow(new Object[]{
                platDisp.getPlatDispos(),
                choix.getQtePlatChoisi(),
                platDisp.getPrixPlatDispos() * quant
            }
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception: " + e.getMessage());
        }
        TCommande.setModel(model);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        //chicken
        String qte = JOptionPane.showInputDialog("Entrez la quantité souhaité: ");
        int quant = Integer.parseInt(qte);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");

        try {

            Client u = ClientDao.getByNom(PropertiesGlobals.USER_CONNECT.getNom());
            if (u != null) {

                PlatChoisis c = new PlatChoisis();
                c.setIdPlat(1);
                c.setQtePlatChoisi(quant);
                System.out.println("idPlat: " + c.getIdPlat());
                PlatChoisisDao.insertPlatsChoisis(c);

                Plat p = new Plat();
                p.setIdPlatDisp(c.getIdPlat());
                p = PlatDao.getPlatById(p.getIdPlatDisp());

            }

            List<Plat> panier = null;

            //panier.add(u);
            PlatChoisis choix = PlatChoisisDao.getLastPlatChoisisById();
            Plat platDisp = PlatDao.getPlatById(1);

            model.addRow(new Object[]{
                platDisp.getPlatDispos(),
                choix.getQtePlatChoisi(),
                platDisp.getPrixPlatDispos() * quant

            }
            );

            //panier.add(platDisp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception: " + e.getMessage());
        }

        TCommande.setModel(model);


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        // steakhouse burger
        String qte = JOptionPane.showInputDialog("Entrez la quantité souhaité: ");
        int quant = Integer.parseInt(qte);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");
        try {
            Client u = ClientDao.getByNom(PropertiesGlobals.USER_CONNECT.getNom());
            if (u != null) {
                PlatChoisis c = new PlatChoisis();
                c.setIdPlat(12);
                c.setQtePlatChoisi(quant);
                System.out.println("idPlat: " + c.getIdPlat());
                PlatChoisisDao.insertPlatsChoisis(c);
                Plat p = new Plat();
                p.setIdPlatDisp(c.getIdPlat());
                p = PlatDao.getPlatById(p.getIdPlatDisp());
            }
            List<Plat> panier = PlatDao.getAllPlatsDisp();
            //panier.add(u);
            PlatChoisis choix = PlatChoisisDao.getLastPlatChoisisById();
            Plat platDisp = PlatDao.getPlatById(12);
            model.addRow(new Object[]{
                platDisp.getPlatDispos(),
                choix.getQtePlatChoisi(),
                platDisp.getPrixPlatDispos() * quant
            }
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception: " + e.getMessage());
        }
        TCommande.setModel(model);

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        // egg burger
        String qte = JOptionPane.showInputDialog("Entrez la quantité souhaité: ");
        int quant = Integer.parseInt(qte);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");

        try {

            Client u = ClientDao.getByNom(PropertiesGlobals.USER_CONNECT.getNom());
            if (u != null) {

                PlatChoisis c = new PlatChoisis();
                c.setIdPlat(10);
                c.setQtePlatChoisi(quant);
                System.out.println("idPlat: " + c.getIdPlat());
                PlatChoisisDao.insertPlatsChoisis(c);

                Plat p = new Plat();
                p.setIdPlatDisp(c.getIdPlat());
                p = PlatDao.getPlatById(p.getIdPlatDisp());

            }

            List<Plat> panier = PlatDao.getAllPlatsDisp();

            //panier.add(u);
            PlatChoisis choix = PlatChoisisDao.getLastPlatChoisisById();
            Plat platDisp = PlatDao.getPlatById(10);

            model.addRow(new Object[]{
                platDisp.getPlatDispos(),
                choix.getQtePlatChoisi(),
                platDisp.getPrixPlatDispos() * quant

            }
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception: " + e.getMessage());
        }

        TCommande.setModel(model);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        //fish
        // fish burger

        String qte = JOptionPane.showInputDialog("Entrez la quantité souhaité: ");
        int quant = Integer.parseInt(qte);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");
        try {

            Client u = ClientDao.getByNom(PropertiesGlobals.USER_CONNECT.getNom());
            if (u != null) {
                PlatChoisis c = new PlatChoisis();
                c.setIdPlat(2);
                c.setQtePlatChoisi(quant);
                System.out.println("idPlat: " + c.getIdPlat());
                PlatChoisisDao.insertPlatsChoisis(c);
                Plat p = new Plat();
                p.setIdPlatDisp(c.getIdPlat());
                p = PlatDao.getPlatById(p.getIdPlatDisp());
            }
            List<Plat> panier = PlatDao.getAllPlatsDisp();
            //panier.add(u);
            PlatChoisis choix = PlatChoisisDao.getLastPlatChoisisById();
            Plat platDisp = PlatDao.getPlatById(2);
            model.addRow(new Object[]{
                platDisp.getPlatDispos(),
                choix.getQtePlatChoisi(),
                platDisp.getPrixPlatDispos() * quant
            }
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception: " + e.getMessage());
        }
        TCommande.setModel(model);

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        
        // king burger
        
        String qte = JOptionPane.showInputDialog("Entrez la quantité souhaité: ");
        int quant = Integer.parseInt(qte);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");
        try {

            Client u = ClientDao.getByNom(PropertiesGlobals.USER_CONNECT.getNom());
            if (u != null) {

                PlatChoisis c = new PlatChoisis();
                c.setIdPlat(11);
                c.setQtePlatChoisi(quant);
                System.out.println("idPlat: " + c.getIdPlat());
                PlatChoisisDao.insertPlatsChoisis(c);
                Plat p = new Plat();
                p.setIdPlatDisp(c.getIdPlat());
                p = PlatDao.getPlatById(p.getIdPlatDisp());
            }
            List<Plat> panier = PlatDao.getAllPlatsDisp();

            //panier.add(u);
            PlatChoisis choix = PlatChoisisDao.getLastPlatChoisisById();
            Plat platDisp = PlatDao.getPlatById(11);
            model.addRow(new Object[]{
                platDisp.getPlatDispos(),
                choix.getQtePlatChoisi(),
                platDisp.getPrixPlatDispos() * quant
            }
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception: " + e.getMessage());
        }
        TCommande.setModel(model);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void ButtonSuivant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSuivant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSuivant1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Article");
        model.addColumn("Qté");
        model.addColumn("Prix");

        TCommande.setModel(model);
    }//GEN-LAST:event_formWindowOpened

    private void CommanderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommanderBtnActionPerformed
        try {
            // VALIDER LA COMMANDE:
            Client u = ClientDao.getLastClientById();
            if (u != null) {

                PlatChoisis c = PlatChoisisDao.getLastPlatChoisisById();

                Commande com = new Commande();
                com.setIdClient(u.getIdClient());
                com.setIdPlatChoisis(c.getIdPlatsChoisis());

                CommandeDao.insertCommande2(com);

            }

        } catch (SQLException ex) {
            Logger.getLogger(CommandeIhm.class
                    .getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_CommanderBtnActionPerformed

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        Bienvenue bv = new Bienvenue();
        bv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommandeIhm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommandeIhm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommandeIhm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommandeIhm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommandeIhm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSuivant1;
    private javax.swing.JButton CommanderBtn;
    private javax.swing.JTable TCommande;
    private javax.swing.JButton btRetour;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
